#!/usr/bin/env fish 
clear
echo ""
echo ""
echo (set_color pink)" ██████╗  ███████╗  ██████╗  ██╗     "
echo (set_color pink)" ██╔══██╗ ██╔════╝ ██╔═══██╗ ██║     "
echo (set_color pink)" ██████╔╝ ███████╗ ██║   ██║ ██║     "
echo (set_color pink)" ██╔═══╝  ╚════██║ ██║▄▄ ██║ ██║     "
echo (set_color pink)" ██║      ███████║ ╚██████╔╝ ███████╗"
echo (set_color pink)" ╚═╝      ╚══════╝  ╚══▀▀═╝  ╚══════╝"
echo (set_color white)""
echo " Connceting using psql - Official postgres client"
echo " Docs - https://www.postgresql.org/docs/current/app-psql.html"
echo ""
echo "Connnecting to the postgres db using psql"
echo "psql connection"
echo ""
echo "Main Command from website"
echo ""
echo "psql -h db.urlqwzlpqnxiduxiwdse.supabase.co -p 5432 -d postgres -U postgres"
echo ""
echo (set_color red)"fart: YermaGEx4wthRB3W" 
echo ""
psql -h db.urlqwzlpqnxiduxiwdse.supabase.co -p 5432 -d postgres -U postgres