import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import {Whisper} from 'next/font/google'
import './globals.css'

const inter = Inter({subsets: ['latin']})
const whisper = Whisper({subsets: ['latin'], weight: '400'})

export const metadata: Metadata = {
	title: 'Ass Juice',
	description: 'Generated by create next app',
}

export default function RootLayout({children}: {children: React.ReactNode}) {
	return (
		<html lang='en'>
			<body className={whisper.className}>{children}</body>
		</html>
	)
}
